# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Degree/Section'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7 - Junior High School'), (8, 'Grade 8 - Junior High School'), (9, 'Grade 9 - Junior High School'), (10, 'Grade 10 - Senior High School'), (11, 'Grade 11 - Senior High School'), (12, 'Grade 12 - Senior High School'), (13, 'Undergraduate'), (14, 'Graduate'), (15, 'Masteral'), (16, 'Doctorate')], null=True, verbose_name='Grade/Year'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City')], max_length=100, null=True),
        ),
    ]
