# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170413_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
    ]
