# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170413_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emergency_contacts',
            new_name='emergency_contact',
        ),
    ]
