# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_date'),
        ('accounts', '0014_waiver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waiver',
            unique_together=set([('userprofile', 'event')]),
        ),
    ]
