# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='Member', to='accounts.UserProfile'),
        ),
    ]
