# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170413_0856'),
        ('affiliations', '0002_auto_20170411_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact'),
        ),
    ]
