# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0004_auto_20170413_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
